language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpspec run -v
  - vendor/bin/phpunit --coverage-text
